### ISSUE TITLE
create signup form

### ISSUE THREAD

**Issue by mohesu-arvind** [mohesu-arvind/myapp#1]
> <ion-header>
    <ion-toolbar>
        <ion-buttons slot="start">
            <ion-menu-button></ion-menu-button>
        </ion-buttons>
        <ion-title>
            Sign up
        </ion-title>
    </ion-toolbar>
</ion-header>
<ion-content>
</ion-content>

[https://github.com/mohesu-arvind/myapp/blob/master/src/app/sign-up/sign-up.page.html](url)

**Comment by ce-akhil** [comment]
You need to add ion form.

**Comment by mohesu-arvind** [comment]
> You need to add ion form.

how to add ion form?
